version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.0.0
    working_directory: ~/app
  android-executor:
    docker:
      - image: cimg/android:2024.04-browsers
    working_directory: ~/app

jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node Dependencies & Capacitor Platforms
          command: |
            rm package-lock.json
            npm i
            npm install @capacitor/core
            npm install @capacitor/cli @capacitor/android @capacitor/ios --save-dev
      - run:
          name: Initialize Capacitor
          command: |
            npx cap init ClashOfCipher app.clashofcipher --web-dir=dist
      - run:
          name: Add Capacitor Platforms (android/ios)
          command: |
            npx cap add android
            npx cap add ios
      - run:
          name: Build Web App
          command: npm run build
      - run:
          name: Capacitor Sync & Copy
          command: |
            npx cap sync
            npx cap copy
      - persist_to_workspace:
          root: .
          paths:
            - .
  android-build:
    executor: android-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Android APK (Gradle)
          command: |
            cd android
            ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: android/app-release.apk
workflows:
  version: 2
  capacitor-build:
    jobs:
      - setup
      - android-build:
          requires:
            - setup
