// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vppefmbjgvfwqqwomfeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwcGVmbWJqZ3Zmd3Fxd29tZmViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTczNzgsImV4cCI6MjA2MjM5MzM3OH0.Lp4kw2SyDSijLOZnSTnIezC6KNcVeY0bPry5-00xUgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);